config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'cas#index'

  resources :cas do
    resources :certificates
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ca.rb
class Ca < ApplicationRecord
  has_many :certificates
end

app/models/certificate.rb
class Certificate < ApplicationRecord
  belongs_to :ca
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cas_controller.rb
class CasController < ApplicationController
  def new
    @ca = Ca.new
  end

  def create
    @ca = Ca.new ca_params

    if @ca.save
      redirect_to cas_path
    else
      render 'new'
    end

  end

  def index
    @cas = Ca.all
  end

  def show
    @ca = Ca.find(params[:id])
  end

  def destroy
    @ca = Ca.find params[:id]
    @ca.destroy

    redirect_to cas_path
  end

  private
  def ca_params
    params.require(:ca).permit(:name)
  end

end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  include OpenSSL

  def new
    @ca = Ca.find params[:ca_id]
  end

  def create
    @ca = Ca.find params[:ca_id]
    @certificate = Certificate.create certificate_params
    @ca.certificates << @certificate
    #------------------------------------------------------
    key = PKey::RSA.new 2048
    name = X509::Name.parse 'CN=fshahy/DC=com'

    cert = X509::Certificate.new
    cert.version = 3
    cert.serial = certificate_params[:serial_number].to_i(16)
    cert.not_before = Time.now
    cert.not_after = Time.now + 3600 * 24 * 365

    cert.public_key = key.public_key
    cert.subject = name
    cert.issuer = name

    ef = X509::ExtensionFactory.new
    bc = ef.create_extension 'basicConstraints', 'CA:TRUE'
    ku = ef.create_extension 'keyUsage', 'keyEncipherment,dataEncipherment,digitalSignature'
    ef.subject_certificate = cert
    ef.issuer_certificate = cert
    ski = ef.create_extension 'subjectKeyIdentifier', 'hash'

    cert.add_extension bc
    cert.add_extension ku
    cert.add_extension ski

    cert.sign key, Digest::SHA256.new

    @certificate.cert_pem = cert.to_pem
    #------------------------------------------------------
    @ca.save
    @certificate.save

    redirect_to ca_path(@ca)
  end

  def index
    puts @ca
  end

  def show
    @ca = Ca.find params[:ca_id]
    @cert = @ca.certificates.find params[:id]
    @certificates = @ca.certificates.all

    puts @cert.cert_pem.to_s
    send_data @cert.cert_pem.to_s, :filename => "#{@cert.serial_number.to_s}.cert"
  end

  private
  def certificate_params
    params.require(:certificate).permit(:ca_id, :subject, :issuer, :serial_number, :not_before, :not_after)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ca_helper.rb
module CaHelper
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/views/cas/_certificates.html.erb
<table border="1">
  <tr>
    <th>Subject</th>
    <th>Issuer</th>
    <th>Serial Number</th>
    <th>NotBefore</th>
    <th>Not After</th>
    <th>Download</th>
  </tr>
  <% @ca.certificates.each do |cert| %>
  <tr>
    <td><%= cert.subject %></td>
    <td><%= cert.issuer %></td>
    <td><%= cert.serial_number %></td>
    <td><%= cert.not_before %></td>
    <td><%= cert.not_after %></td>
    <td><%= link_to "#{cert.serial_number}", ca_certificate_path(@ca, cert) %></td>
  </tr>
  <% end %>
</table>

app/views/cas/_form.html.erb
<%= form_with model: @ca do |form| %>
Name: <%= form.text_field :name, :id => :name %> <br/>
<%= form.submit 'Submit' %>
<%= link_to 'Back', cas_path %>
<% end %>

app/views/cas/index.html.erb
<h1>Certificate Authorities (CA)</h1>
<%= link_to 'New CA', new_ca_path %>

<table border="1">
  <tr>
    <th>Name</th>
    <th></th>
  </tr>

  <% @cas.each do |ca| %>
  <tr>
    <td>
      <%= ca.name %>
    </td>
    <td>
      <%= link_to 'Show', ca_path(ca) %>
    </td>
  </tr>
  <% end %>
</table

app/views/cas/new.html.erb
<h1>Create new CA</h1>

<%= render 'form' %>

app/views/cas/show.html.erb
<h1>CA Info</h1>

<%= render 'form' %>

<%= link_to 'New Certificate', new_ca_certificate_path(@ca) %>
<%= render 'certificates' %>

app/views/certificates/_form.html.erb
<%= form_with(model: [ @ca, @ca.certificates.build ])  do |form| %>
Subject: <%= form.text_field :subject, :id => :subject %> <br/>
Issuer: <%= form.text_field :issuer, :id => :issuer %> <br/>
Serial Number: <%= form.text_field :serial_number, :id => :serial_number %> <br/>
Not Before: <%= form.text_field :not_before, :id => :not_before %> <br/>
Not After: <%= form.text_field :not_after, :id => :not_after %> <br/>
<%= form.submit 'Submit' %>
<%= link_to 'Back', ca_path(@ca) %>
<% end %>

app/views/certificates/index.html.erb
<h1>CA Certificates</h1>
<%= link_to 'New Certificate', new_certificate_path %>

<table border="1">
  <tr>
    <th>Name</th>
    <th>Serial Number</th>
    <th></th>
    <th></th>
  </tr>

  <% @certificates.each do |cert| %>
  <tr>
    <td>
      <%= cert.subject %>
    </td>
    <td>
      <%= cert.serial_number %>
    </td>
    <td>
      <%= link_to 'Show', certificate_path(cert) %>
    </td>
    <td>
      <%= link_to 'Remove', certificate_path(cert),
          method: :delete,
          data: {confirm: 'Are you sure?'}
      %>
    </td>
  </tr>
  <% end %>
</table

app/views/certificates/new.html.erb
<h1>Create new Certificate</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Certify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>